general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    # inhibit_sleep = 0  # Optional: Ensure sleep inhibition is disabled if you want to override system defaults.
}

# Lock the screen after 5 minutes.
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off screen after 6 minutes.
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Shut down the system after 1 hour.
# Add this to sudoers file using visudo:
# ```text
# yourusername ALL=(ALL) NOPASSWD: /usr/sbin/shutdown
#```
listener {
    timeout = 3600
    on-timeout = shutdown now
}
